# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  Shopdb:
    Url: jdbc:postgresql://test-db.ivyteam.io/IvyTgr
    Driver: org.postgresql.Driver
    UserName: postgres
    Password: ${decrypt:LtEQqeGP4ndLIOemOynoXA==}
